title: "FEDERICO-KAKAZU-Portfolio 2022"
author: "Federico Kakazu"
description: "Â© 2022. All rights reserved. - Made with <b style=\"color: #f45;\">red word</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:fedekakazu@gmail.com"}
  - {title: G-Behance, icon: behance, url: "https://www.behance.net/FedeK/projects"}
  - {title: S-Instagram, icon: instagram, url: "/feed.xml"}
  - {title: LinkedIn, icon: linkedin, url: "/feed.xml"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
